"""Subclass of DataImport, which is generated by wxFormBuilder."""

import wx
import frame.mainframe as mainframe

# Implementing DataImport
class FDataImportEvent( mainframe.FDataImport ):
	def __init__( self, parent ):
		mainframe.FDataImport.__init__( self, parent )

	# Handlers for DataImport events.
	def m_filePicker1OnFileChanged( self, event ):
			
		# TODO: Implement m_filePicker1OnFileChanged
		pass
	
	
