"""Subclass of FForm, which is generated by wxFormBuilder."""

import wx
import frame.mainframe as mainframe

# Implementing FForm
class FFormEvent( mainframe.FForm ):
    def __init__( self, parent ):
        mainframe.FForm.__init__( self, parent )
    
    # Handlers for FForm events.
    def m_textCtrl1OnText( self, event ):
        # TODO: Implement m_textCtrl1OnText
        print(self.m_textCtrl1.GetValue())
        pass
    
    def m_textCtrl2OnText( self, event ):
        # TODO: Implement m_textCtrl2OnText
        pass
    
    def m_textCtrl3OnText( self, event ):
        # TODO: Implement m_textCtrl3OnText
        pass
    
    def m_textCtrl4OnText( self, event ):
        # TODO: Implement m_textCtrl4OnText
        pass
    
    def m_textCtrl5OnText( self, event ):
        # TODO: Implement m_textCtrl5OnText
        pass
    
    def m_textCtrl6OnText( self, event ):
        # TODO: Implement m_textCtrl6OnText
        pass
    
    def m_button1OnButtonClick( self, event ):
        # TODO: Implement m_button1OnButtonClick
        pass
    
    def m_button2OnButtonClick( self, event ):
        # TODO: Implement m_button2OnButtonClick
        print(self.m_textCtrl1.GetValue())
        print(self.m_textCtrl2.GetValue())
        print(self.m_textCtrl3.GetValue())
        print(self.m_textCtrl4.GetValue())
        print(self.m_textCtrl5.GetValue())
        print(self.m_textCtrl6.GetValue())
        print("okay")
        pass
    
    
