"""Subclass of FPengaturan, which is generated by wxFormBuilder."""

import wx
import frame.mainframe as mainframe
import frame.CForm

# Implementing FPengaturan
class FPengaturanEvent( mainframe.FPengaturan ):
    def __init__( self, parent ):
        mainframe.FPengaturan.__init__( self, parent )
        self.bukaform = frame.CForm.FFormEvent(self)

    # Handlers for FPengaturan events.
    def m_button18OnButtonClick( self, event ):
        # TODO: Implement m_button18OnButtonClick
        pass
    
    def m_button19OnButtonClick( self, event ):
        # TODO: Implement m_button19OnButtonClick
        print ("hello")
        try:
            self.bukaform.Show()
        except:
            self.bukaform = frame.CForm.FFormEvent(self)
            self.bukaform.Show()
        event.Skip()
        pass
    
    def m_button20OnButtonClick( self, event ):
        # TODO: Implement m_button20OnButtonClick
        pass
    
    def m_button21OnButtonClick( self, event ):
        # TODO: Implement m_button21OnButtonClick
        pass
    
    def m_button22OnButtonClick( self, event ):
        # TODO: Implement m_button22OnButtonClick
        pass
    
    def m_button23OnButtonClick( self, event ):
        # TODO: Implement m_button23OnButtonClick
        pass
    
    
