"""Subclass of FPenjualan, which is generated by wxFormBuilder."""

import wx
import frame.mainframe as mainframe

# Implementing FPenjualan
class FPenjualanEvent( mainframe.FPenjualan ):
    def __init__( self, parent ):
        mainframe.FPenjualan.__init__( self, parent )
        self.Maximize(True)

        self.mycolumns=["A","B","C","D","E"]
        self.mywidth=[50,250,300,200,200]
        self.heading = list(self.mycolumns)
        self.__setlistctrl__()
        
    def __setlistctrl__(self):
        l = [self.m_listCtrl1.InsertColumn(i,heading=(str(self.heading[i])), \
        width=self.mywidth[i]) for i in range(len(self.mycolumns))]

    # Handlers for FPenjualan events.
    def FPenjualanOnClose( self, event ):
        # TODO: Implement FPenjualanOnClose
        self.Destroy()
        pass
    def FPenjualanOnChar( self, event ):
        
        self.Destroy()
        pass
   
    def m_textCtrl13OnText( self, event ):
        print (self.m_textCtrl13.GetValue())
        print ("This is working")
        pass
    
    def m_button161OnButtonClick( self, event ):
        print ("This is working")
        pass
    
    def m_button17OnButtonClick( self, event ):
        print ("This is working")
        pass
    
    def m_button18OnButtonClick( self, event ):
        print ("This is working")
        pass
    
    def m_button19OnButtonClick( self, event ):
        print ("This is working")
        pass
    
    def m_button14OnButtonClick( self, event ):
        print ("This is working")
        pass
    
    def m_button15OnButtonClick( self, event ):
        print ("This is working")
        pass
    
    def m_button16OnButtonClick( self, event ):
        print ("This is working")
        pass
    
    def m_tool3OnToolClicked( self, event ):
        print ("This is working")
        pass
    
    def m_tool4OnToolClicked( self, event ):
        print ("This is working")
        pass
    
    def m_tool5OnToolClicked( self, event ):
        pass
    
    def m_tool6OnToolClicked( self, event ):
        pass
    