"""Subclass of FPenjualan, which is generated by wxFormBuilder."""
#import wx.Event
import wx
import frame.mainframe as mainframe

# Implementing FPenjualan
class FPenjualanEvent( mainframe.FPenjualan ):
    def __init__( self, parent ):
        mainframe.FPenjualan.__init__( self, parent )
        self.Maximize(True)
        self.mycolumns=["A","B","C","D","E"]
        self.mywidth=[50,250,300,200,200]
        self.heading = list(self.mycolumns)
        self.__setlistctrl__()
        
    def __setlistctrl__(self):
        l = [self.m_listCtrl1.InsertColumn(i,heading=(str(self.heading[i])), \
        width=self.mywidth[i]) for i in range(len(self.mycolumns))]

    # Handlers for FPenjualan events.
    def FPenjualanOnClose( self, event ):
        #TODO: Implement FPenjualanOnClose
        self.Destroy()
        pass
    
    def m_textCtrl13OnText( self, event ):
        print (self.m_textCtrl13.GetValue())
        print ("This is working")
        pass

    def m_textCtrl13OnKeyDown( self, event ):
        if event.GetKeyCode() == wx.WXK_ESCAPE:
            print ("it's working, YOU press Escape so it\
            will close the frame Penjualan")
            self.FPenjualanOnClose(self)
        elif event.GetKeyCode()== wx.WXK_DELETE:
            print ("it should make the text box clear")
        else :
            print ("youre not doing the right thing,it's not working")
        event.Skip()
        pass    
   
    def m_textCtrl13OnTextEnter( self, event ):
        print ("this is work")
        pass
   
    def m_tool3OnToolClicked( self, event ):
        event.Skip()
    
    def m_tool4OnToolClicked( self, event ):
        event.Skip()
    
    def m_tool5OnToolClicked( self, event ):
        event.Skip()
    
    def m_tool6OnToolClicked( self, event ):
        pass

 
