"""Subclass of FUtama, which is generated by wxFormBuilder."""

import wx
import frame.mainframe as mainframe
import frame.CPenjualan
import frame.CPengaturan

# Implementing FUtama
class FUtamaEvent( mainframe.FUtama ):
    def __init__( self, parent ):
        mainframe.FUtama.__init__( self, parent )
        print (FUtamaEvent.__doc__)
        self.framepenj = frame.CPenjualan.FPenjualanEvent(self)
        self.framepeng = frame.CPengaturan.FPengaturanEvent(self)
    
    # Handlers for FUtama events.
    def FUtamaOnClose( self, event ):
        # TODO: Implement FUtamaOnClose
        try:
            self.framepenj.Destroy()
            self.framepeng.Destroy()
            self.Destroy()
        except:
            self.Destroy()
        event.Skip()
        pass
    
    def m_button1OnButtonClick( self, event ):
        # TODO: Implement m_button1OnButtonClick
        try:
            self.framepenj.Maximize()
            self.framepenj.Show()
        except:
            self.framepenj =  frame.CPenjualan.FPenjualanEvent(self)
            self.framepenj.Maximize()
            self.framepenj.Show()
        event.Skip()
        pass
    
    def m_button2OnButtonClick( self, event ):
        # TODO: Implement m_button2OnButtonClick
        try:
            self.framepeng.Show()
        except:
            self.framepeng = mainframe.frame.CPengaturan.FPengaturanEvent(self)
            self.framepeng.Show()
        event.Skip()
        pass
    
    def m_button3OnButtonClick( self, event ):
        # TODO: Implement m_button3OnButtonClick
        pass
    
    def m_button4OnButtonClick( self, event ):
        # TODO: Implement m_button4OnButtonClick
        pass
    
    def m_button5OnButtonClick( self, event ):
        # TODO: Implement m_button5OnButtonClick
        pass
    
    def m_menuItem2OnMenuSelection( self, event ):
        # TODO: Implement m_menuItem2OnMenuSelection
        pass
    
    
