"""Subclass of FDialog, which is generated by wxFormBuilder."""

import wx
import mainframe

# Implementing FDialog
class FDialogEvent( mainframe.FDialog ):
	def __init__( self, parent ):
		mainframe.FDialog.__init__( self, parent )
	
