"""Subclass of FForm, which is generated by wxFormBuilder."""

import wx

import frame.mainframe as mainframe


# Implementing FForm
class FFormEvent( mainframe.FForm ):
    def __init__( self, parent ):
        mainframe.FForm.__init__( self, parent )
    
        self.custom_event()
    
    def custom_event(self):   
        # Connect Events
        self.m_panel2.Bind(wx.EVT_CHAR_HOOK,self.m_panelOnChar)
        self.m_textCtrl1.Bind( wx.EVT_TEXT, self.datatext1 )
        self.m_textCtrl2.Bind( wx.EVT_TEXT, self.datatext2 )
        self.m_textCtrl3.Bind( wx.EVT_TEXT, self.datatext3 )
        self.m_textCtrl4.Bind( wx.EVT_TEXT, self.datatext4 )
        self.m_textCtrl5.Bind( wx.EVT_TEXT, self.datatext5 )
        self.m_textCtrl6.Bind( wx.EVT_TEXT, self.datatext5 )
        self.m_button1.Bind( wx.EVT_BUTTON, self.batal )
        self.m_button2.Bind( wx.EVT_BUTTON, self.ok )        
    
     # Handlers for FForm events.
    def m_panelOnChar(self,event):
        print (event.GetKeyCode)
        if event.GetKeyCode() == wx.WXK_ESCAPE:
            self.Destroy()
            print ("okay")
        else:
            print ("wrong")
        event.Skip()

    def datatext1( self, event ):
        # TODO: Implement datatext1
        print(self.m_textCtrl1.GetValue())
        pass
    
    def datatext2( self, event ):
        # TODO: Implement datatext2
        pass
    
    def datatext3( self, event ):
        # TODO: Implement datatext3
        pass
    
    def datatext4( self, event ):
        # TODO: Implement datatext4
        pass
    
    def datatext5( self, event ):
        # TODO: Implement datatext5
        pass
    
    def datatext5( self, event ):
        # TODO: Implement datatext5
        pass
    
    def batal( self, event ):
        # TODO: Implement batal
        pass
    
    def ok( self, event ):
        # TODO: Implement ok
        print(self.m_textCtrl1.GetValue())
        print(self.m_textCtrl2.GetValue())
        print(self.m_textCtrl3.GetValue())
        print(self.m_textCtrl4.GetValue())
        print(self.m_textCtrl5.GetValue())
        print(self.m_textCtrl6.GetValue())
        print("okay")
        pass
