"""Subclass of FPenjualan, which is generated by wxFormBuilder."""

import wx
import mainframe

# Implementing FPenjualan
class Projects2FPenjualan( mainframe.FPenjualan ):
	def __init__( self, parent ):
		mainframe.FPenjualan.__init__( self, parent )
	
