"""Subclass of Form2, which is generated by wxFormBuilder."""

import wx
import form

# Implementing Form2
class guiForm2( form.Form2 ):
	def __init__( self, parent ):
		form.Form2.__init__( self, parent )
	
