"""Subclass of Form1, which is generated by wxFormBuilder."""

import wx
import form

# Implementing Form1
class guiForm1( form.Form1 ):
	def __init__( self, parent ):
		form.Form1.__init__( self, parent )
	
	# Handlers for Form1 events.
	def m_textCtrl1OnText( self, event ):
		# TODO: Implement m_textCtrl1OnText
		pass
	
	def m_textCtrl2OnText( self, event ):
		# TODO: Implement m_textCtrl2OnText
		pass
	
	def m_textCtrl3OnText( self, event ):
		# TODO: Implement m_textCtrl3OnText
		pass
	
	def m_textCtrl4OnText( self, event ):
		# TODO: Implement m_textCtrl4OnText
		pass
	
	def m_textCtrl5OnText( self, event ):
		# TODO: Implement m_textCtrl5OnText
		pass
	
	def m_textCtrl6OnText( self, event ):
		# TODO: Implement m_textCtrl6OnText
		pass
	
	def m_button1OnButtonClick( self, event ):
		# TODO: Implement m_button1OnButtonClick
		pass
	
	def m_button2OnButtonClick( self, event ):
		# TODO: Implement m_button2OnButtonClick
		pass
	
	
