"""Subclass of Form3, which is generated by wxFormBuilder."""

import wx
import form

# Implementing Form3
class guiForm3( form.Form3 ):
	def __init__( self, parent ):
		form.Form3.__init__( self, parent )
	
